# Generated by Django 5.2 on 2025-04-21 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
